<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.1.0" />
    <PackageReference Include="FastEndpoints.Security" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CondominiumManager.Condominium\CondominiumManager.Condominium.csproj" />
    <ProjectReference Include="..\CondominiumManager.Finance\CondominiumManager.Finance.csproj" />
    <ProjectReference Include="..\CondominiumManager.Identity\CondominiumManager.Identity.csproj" />
    <ProjectReference Include="..\CondominiumManager.Notifications\CondominiumManager.Notifications.csproj" />
    <ProjectReference Include="..\InfraStructure\InfraStructure.csproj" />
    <ProjectReference Include="..\Sharedkernel\Sharedkernel.csproj" />
  </ItemGroup>

</Project>
