<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Application\Queries\**" />
    <Compile Remove="IdentityEndPoints\**" />
    <EmbeddedResource Remove="Application\Queries\**" />
    <EmbeddedResource Remove="IdentityEndPoints\**" />
    <None Remove="Application\Queries\**" />
    <None Remove="IdentityEndPoints\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="UserEndPoints\Register.Validator.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.1.0" />
    <PackageReference Include="FastEndpoints.Security" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\Contracts\Results\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="UserEndPoints\Validators\UserRequestValidator.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InfraStructure\InfraStructure.csproj" />
    <ProjectReference Include="..\Sharedkernel\Sharedkernel.csproj" />
  </ItemGroup>

</Project>
